name: "OCR Server"
slug: "ocr_server"
version: "0.1.3"
description: "OCR server (config file stored in /config)"
arch:
  - amd64
startup: services
boot: auto

ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "OCR HTTP API"

map:
  - config:rw

options:
  config_path: "/config/ocr_server/config.yaml"

  mqtt_host: "192.168.0.90"
  mqtt_port: 1883
  mqtt_username: "mqtt"
  mqtt_password: ""
  mqtt_topic_base: "meters"

schema:
  config_path: str

  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  mqtt_topic_base: str


schema:
  config_path: str

